#!/bin/sh
ECHO="/bin/echo"
MOUNT="/bin/mount"

${ECHO} -e "\033[031m*** Debian Stage 1: Setup system and device drivers ***\033[0m"
# set LED to blink green
setLED SYS GREEN BLINK

# Mount procfs and sysfs for ifconfig and hwclock
${MOUNT} -t devtmpfs devtmpfs /dev
${MOUNT} -t proc /proc /proc
${MOUNT} -t sysfs /sys /sys
${MOUNT} -t usbfs none /proc/bus/usb
${MOUNT} -t devpts devpts /dev/pts

${MOUNT} -t tmpfs tmpfs /tmp

if [ ! -e /etc/.zy-first.done ]; then
  /usr/local/bin/zy-nand-get
  if [ ! -e /firmware/sbin/mrd_mac ]; then
    /usr/local/bin/zy-init-get
  fi
fi

/usr/local/bin/zy-hw-init
touch /tmp/.dru-hw-init.done

setLED SYS GREEN BLINK

if [ -e /sbin/halt.distrib ]; then
  ln -sf /sbin/halt.distrib /sbin/halt
fi

if [ -e /sbin/reboot.distrib ]; then
  ln -sf /sbin/reboot.distrib /sbin/reboot
fi

if [ -e /bin/systemctl.distrib -a -e /bin/systemctl.druic ]; then
  ln -sf /bin/systemctl.distrib /bin/systemctl
fi

if [ -e /etc/network/if-up.d/openmediavault-issue ]; then
  sed -i s/'^omv-mkconf issue'/'#omv-mkconf issue'/g /etc/network/if-up.d/openmediavault-issue
fi

${ECHO} -e "\033[031m*** Debian Stage 2: Run init ***\033[0m"

exec /sbin/init
